Repository UiPath/angular-components, pull requests merged in 2019-06, with the labels that each got.

#25 Improve README and add lib package metadata
  .npmrc
  README.md
  package.json
  projects/angular/package.json
Labels: enhancement

#27 Fix / UiGridModule barreled exports
  CHANGELOG.md
  package.json
  projects/angular/components/src/public_api.ts
  projects/angular/components/src/ui-grid/body/index.ts
  projects/angular/components/src/ui-grid/body/ui-grid-column.directive.ts
  projects/angular/components/src/ui-grid/components/index.ts
  projects/angular/components/src/ui-grid/components/ui-grid-search/index.ts
  projects/angular/components/src/ui-grid/filters/index.ts
  projects/angular/components/src/ui-grid/footer/index.ts
  projects/angular/components/src/ui-grid/header/index.ts
  projects/angular/components/src/ui-grid/managers/filter-manager.spec.ts
  projects/angular/components/src/ui-grid/managers/filter-manager.ts
  projects/angular/components/src/ui-grid/managers/resize/resize-manager.ts
  projects/angular/components/src/ui-grid/managers/resize/strategies/aggresive-neighbour-push-resizer.ts
  projects/angular/components/src/ui-grid/managers/resize/types/resizableGrid.ts
  projects/angular/components/src/ui-grid/managers/resize/types/resizeInfo.ts
  projects/angular/components/src/ui-grid/managers/sort-manager.spec.ts
  projects/angular/components/src/ui-grid/test/column.ts
  projects/angular/components/src/ui-grid/ui-grid.component.spec.ts
  projects/angular/components/src/ui-grid/ui-grid.component.ts
  projects/angular/components/src/ui-grid/ui-grid.intl.ts
  projects/angular/components/src/ui-grid/ui-grid.module.ts
  projects/angular/package.json
Labels: bug

#29 CI / Extract Build Subtasks and Generate Build Artifacts
  .ci/templates/steps/create-bundle.yml
  .ci/templates/steps/initialize-environment.yml
  .ci/templates/steps/test.yml
  azure-pipelines.yml
  package.json
Labels: enhancement

#28 Commitizen + Husky + CommitLint + Conventional-Commits = 💖
  README.md
  commitlint.config.js
  package-lock.json
  package.json
Labels: enhancement

#31 chore: configure commitlint scopes
  commitlint.config.js
Labels: enhancement

#30 Refactor to eliminate code smells and configure codeclimate
  .codeclimate.yml
  projects/angular/components/src/ui-grid/managers/filter-manager.ts
  projects/angular/components/src/ui-grid/managers/selection-manager.ts
  projects/angular/directives/src/internal/ui-format.ts
  projects/angular/directives/src/ui-dateformat/ui-dateformat.directive.ts
  projects/angular/directives/src/ui-secondformat/ui-secondformat.directive.ts
Labels: enhancement

#32 Feature / Upgrade - angular@8
  .ci/templates/steps/initialize-environment.yml
  package-lock.json
  package.json
  projects/angular/components/src/ui-grid/body/ui-grid-column.directive.spec.ts
  projects/angular/components/src/ui-grid/body/ui-grid-column.directive.ts
  projects/angular/components/src/ui-grid/body/ui-grid-expanded-row.directive.ts
  projects/angular/components/src/ui-grid/body/ui-grid-row-action.directive.ts
  projects/angular/components/src/ui-grid/components/ui-grid-search/ui-grid-search.component.spec.ts
  projects/angular/components/src/ui-grid/filters/ui-grid-dropdown-filter.directive.ts
  projects/angular/components/src/ui-grid/filters/ui-grid-search-filter.directive.ts
  projects/angular/components/src/ui-grid/header/ui-grid-header-button.directive.ts
  projects/angular/components/src/ui-grid/ui-grid.component.spec.ts
  projects/angular/components/src/ui-grid/ui-grid.component.ts
  projects/angular/components/src/ui-suggest/ui-suggest.component.spec.ts
  projects/angular/components/src/ui-suggest/ui-suggest.component.ts
  projects/angular/directives/src/ui-dateformat/ui-dateformat.directive.spec.ts
  projects/angular/directives/src/ui-scroll-into-view/ui-scroll-into-view.directive.spec.ts
  projects/angular/directives/src/ui-secondformat/ui-secondformat.directive.spec.ts
  projects/angular/directives/src/ui-virtual-scroll-range-loader/ui-virtual-scroll-range-loader.directive.spec.ts
  projects/angular/directives/src/ui-virtual-scroll-range-loader/ui-virtual-scroll-range-loader.directive.ts
  projects/angular/directives/src/ui-virtual-scroll-viewport-resize/ui-virtual-scroll-viewport-resize.directive.spec.ts
  tsconfig.json
  tslint.json
Labels: bug, enhancement

#33 Feature / Commitlint status check
  .build/commitlint/index.js
  .build/commitlint/package-lock.json
  .build/commitlint/package.json
  .ci/templates/steps/initialize-environment.yml
  .ci/templates/steps/install-dependencies.yml
  .gitignore
  azure-pipelines.yml
Labels: enhancement

#35 Fix / Publish test results when task fails
  .ci/templates/steps/test.yml
Labels: bug

#36 Sync Master With Current Release
  CHANGELOG.md
  package.json
  projects/angular/components/src/ui-grid/ui-grid.component.html
  projects/angular/components/src/ui-grid/ui-grid.component.spec.ts
  projects/angular/package.json
Labels: bug

#37 Feature / publish docs automatically on master builds
  .build/commitlint/index.js
  .build/common/index.js
  .build/publish-gh-pages.js
  .build/publish-gh-pages/index.js
  .ci/templates/steps/initialize-environment.yml
  azure-pipelines.yml
  package.json
Labels: enhancement

#39 Feature / Allow ngLet content to be queried statically
  projects/angular/directives/src/ui-ng-let/ui-ng-let.directive.spec.ts
  projects/angular/directives/src/ui-ng-let/ui-ng-let.directive.ts
Labels: enhancement

#42 Fix / UiSuggest / chore: remove tap warn from scroll directive
  projects/angular/directives/ui-virtual-scroll-range-loader/src/ui-virtual-scroll-range-loader.directive.ts
Labels: bug
