Repository UiPath/angular-components, pull requests merged in 2021-03, with the labels that each got.

#120 feat(scroll-into-view): add input to configure the block param
  projects/angular/directives/ui-scroll-into-view/src/ui-scroll-into-view.directive.ts
Labels: enhancement

#133 fix(password-indicator): implement proper a11y support
  projects/angular/components/ui-password-indicator/src/ui-password-indicator.component.html
  projects/angular/components/ui-password-indicator/src/ui-password-indicator.component.ts
  projects/angular/components/ui-password-indicator/src/ui-password-indicator.intl.ts
Labels: a11y, enhancement

#136 fix(a11y): add mat-icon[tabindex] to auto-accessible-label directive
  projects/angular/a11y/src/ui-auto-accessible-label/ui-auto-accessible-label.directive.ts
Labels: a11y

#135 fix: a11y grid
  CHANGELOG.md
  package-lock.json
  package.json
  projects/angular/components/ui-grid/src/body/ui-grid-column.directive.spec.ts
  projects/angular/components/ui-grid/src/body/ui-grid-column.directive.ts
  projects/angular/components/ui-grid/src/managers/selection-manager.spec.ts
  projects/angular/components/ui-grid/src/managers/selection-manager.ts
  projects/angular/components/ui-grid/src/ui-grid.component.html
  projects/angular/components/ui-grid/src/ui-grid.component.spec.ts
  projects/angular/components/ui-grid/src/ui-grid.component.ts
  projects/angular/components/ui-grid/src/ui-grid.intl.ts
  projects/angular/directives/ui-drag-and-drop-file/src/ui-drag-and-drop-file.directive.spec.ts
  projects/angular/directives/ui-drag-and-drop-file/src/ui-drag-and-drop-file.directive.ts
  projects/angular/package.json
  projects/angular/testing/src/utilities/event-generator.ts
Labels: a11y, enhancement
